name: Deploy
on:
  workflow_run:
    workflows: ["Release"]
    branches: [ 'release/*' ]
    types:
      - completed
jobs:
  Deploy_release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install project
        run: npm install
      - name: Instal IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
          ibmcloud plugin install -f cloud-object-storage
      - name: Compile production build
        env:
          PUBLIC_URL: ${{ secrets.WEBPACK_PUBLIC_URL }}
        run: NODE_ENV=production npm run build
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Deploy to Cloud Object Storage
        env:
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
          IBM_CLOUD_RESOURCE_ID: ${{ secrets.IBM_CLOUD_RESOURCE_ID }}
          IBM_CLOUD_BUCKET: ${{ secrets.IBM_CLOUD_BUCKET }}
        run: bash ./.github/scripts/cos-upload.sh ./build ${{steps.extract_branch.outputs.branch}}
      - name: Publish storybook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.kyndryl.net/${GITHUB_REPOSITORY}.git
          npx build-storybook
          npx gh-pages -d storybook-static -u "github-actions-bot <support+actions@github.com>"